[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.0"
anyhow = "1.0.100"
dotenv = "0.15.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = "1.48.0"
db = { path = "../db" }
